//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeepConfigEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ActionsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeepConfigEditor.Resources.ActionsRes", typeof(ActionsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        public static string AboutCaption {
            get {
                return ResourceManager.GetString("AboutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new section....
        /// </summary>
        public static string AddSectionCaption {
            get {
                return ResourceManager.GetString("AddSectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new section to the current configuration..
        /// </summary>
        public static string AddSectionTooltip {
            get {
                return ResourceManager.GetString("AddSectionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        public static string AlwaysOnTopCaption {
            get {
                return ResourceManager.GetString("AlwaysOnTopCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Crypto Provider....
        /// </summary>
        public static string AssignCryptoCaption {
            get {
                return ResourceManager.GetString("AssignCryptoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign the cryptography provider to use for this configuration..
        /// </summary>
        public static string AssignCryptoTooltip {
            get {
                return ResourceManager.GetString("AssignCryptoTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate with config files.
        /// </summary>
        public static string AssociateWithCaption {
            get {
                return ResourceManager.GetString("AssociateWithCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can associate files with the .config extension to use this editor by default.
        ///You can always revert to the previous association by unselecting this option..
        /// </summary>
        public static string AssociateWithDescription {
            get {
                return ResourceManager.GetString("AssociateWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate config files with this editor..
        /// </summary>
        public static string AssociateWithTooltip {
            get {
                return ResourceManager.GetString("AssociateWithTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all sections.
        /// </summary>
        public static string CollapseSectionsCaption {
            get {
                return ResourceManager.GetString("CollapseSectionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete configuration.
        /// </summary>
        public static string DeleteCaption {
            get {
                return ResourceManager.GetString("DeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the current configuration from storage..
        /// </summary>
        public static string DeleteTooltip {
            get {
                return ResourceManager.GetString("DeleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string ExitCaption {
            get {
                return ResourceManager.GetString("ExitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all sections.
        /// </summary>
        public static string ExpandSectionsCaption {
            get {
                return ResourceManager.GetString("ExpandSectionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        public static string ExtensionsCaption {
            get {
                return ResourceManager.GetString("ExtensionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpCaption {
            get {
                return ResourceManager.GetString("HelpCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Recent.
        /// </summary>
        public static string MruCaption {
            get {
                return ResourceManager.GetString("MruCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string NewCaption {
            get {
                return ResourceManager.GetString("NewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new configuration..
        /// </summary>
        public static string NewTooltip {
            get {
                return ResourceManager.GetString("NewTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string OpenCaption {
            get {
                return ResourceManager.GetString("OpenCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an existing configuration..
        /// </summary>
        public static string OpenTooltip {
            get {
                return ResourceManager.GetString("OpenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        public static string OptionsCaption {
            get {
                return ResourceManager.GetString("OptionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsHeaderCaption {
            get {
                return ResourceManager.GetString("OptionsHeaderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the options for the editor..
        /// </summary>
        public static string OptionsTooltip {
            get {
                return ResourceManager.GetString("OptionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshCaption {
            get {
                return ResourceManager.GetString("RefreshCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload the currently open configuration..
        /// </summary>
        public static string RefreshTooltip {
            get {
                return ResourceManager.GetString("RefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _as....
        /// </summary>
        public static string SaveAsCaption {
            get {
                return ResourceManager.GetString("SaveAsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current configuration to a new location..
        /// </summary>
        public static string SaveAsTooltip {
            get {
                return ResourceManager.GetString("SaveAsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string SaveCaption {
            get {
                return ResourceManager.GetString("SaveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to the currently open configuration..
        /// </summary>
        public static string SaveTooltip {
            get {
                return ResourceManager.GetString("SaveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show unsupported sections.
        /// </summary>
        public static string ShowUnsupportedCaption {
            get {
                return ResourceManager.GetString("ShowUnsupportedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show an entry for all sections that could not be read by the editor, with an explanation why..
        /// </summary>
        public static string ShowUnsupportedTooltip {
            get {
                return ResourceManager.GetString("ShowUnsupportedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string SourceCaption {
            get {
                return ResourceManager.GetString("SourceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewCaption {
            get {
                return ResourceManager.GetString("ViewCaption", resourceCulture);
            }
        }
    }
}
