//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeepConfigEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigSourceSelectRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigSourceSelectRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeepConfigEditor.Resources.ConfigSourceSelectRes", typeof(ConfigSourceSelectRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration source selection.
        /// </summary>
        public static string ConfigSelectStatusMessage {
            get {
                return ResourceManager.GetString("ConfigSelectStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a config file by browsing the file system:.
        /// </summary>
        public static string FileOpenOptionOne {
            get {
                return ResourceManager.GetString("FileOpenOptionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or open one of the recently edited config files:.
        /// </summary>
        public static string FileOpenOptionTwo {
            get {
                return ResourceManager.GetString("FileOpenOptionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember last opened location.
        /// </summary>
        public static string FileRememberLastLocation {
            get {
                return ResourceManager.GetString("FileRememberLastLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the directory of the chosen file will be remembered and used as the starting directory the next time you browse for a file..
        /// </summary>
        public static string FileRememberLastLocationTooltip {
            get {
                return ResourceManager.GetString("FileRememberLastLocationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or create a config file by browsing the file system:.
        /// </summary>
        public static string FileSaveOption {
            get {
                return ResourceManager.GetString("FileSaveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or create the configuration file to save to..
        /// </summary>
        public static string FileSaveTitle {
            get {
                return ResourceManager.GetString("FileSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Files (*.config)|*.config|XML Files (*.xml)|*.xml|All Files (*.*)|*.*.
        /// </summary>
        public static string FileSelectFilter {
            get {
                return ResourceManager.GetString("FileSelectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the configuration file to open..
        /// </summary>
        public static string FileSelectTitle {
            get {
                return ResourceManager.GetString("FileSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no recent sources.
        /// </summary>
        public static string NoRecentSources {
            get {
                return ResourceManager.GetString("NoRecentSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string RecentSources {
            get {
                return ResourceManager.GetString("RecentSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveRecentSource {
            get {
                return ResourceManager.GetString("RemoveRecentSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (reset).
        /// </summary>
        public static string ResetLocationCaption {
            get {
                return ResourceManager.GetString("ResetLocationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets the starting directory to the default (Desktop).
        /// </summary>
        public static string ResetLocationTooltip {
            get {
                return ResourceManager.GetString("ResetLocationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No configuration is currently open for editing.
        ///You could open one, create a new one or choose one of the recently edited configurations..
        /// </summary>
        public static string StartScreenIntro {
            get {
                return ResourceManager.GetString("StartScreenIntro", resourceCulture);
            }
        }
    }
}
