//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeepConfigEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeepConfigEditor.Resources.MessagesRes", typeof(MessagesRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error deleting the configuration.
        ///
        ///If this continues, please inspect the log for the most recent error and report the problem.
        ///The error log can be opened by clicking the link below..
        /// </summary>
        public static string ConfigDeleteError {
            get {
                return ResourceManager.GetString("ConfigDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete the configuration:
        ///
        ///{0}.
        /// </summary>
        public static string ConfigDeleteWarning {
            get {
                return ResourceManager.GetString("ConfigDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading the configuration.
        ///
        ///If this continues, please inspect the log for the most recent error and report the problem.
        ///The error log can be opened by clicking the link below..
        /// </summary>
        public static string ConfigLoadError {
            get {
                return ResourceManager.GetString("ConfigLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing will discard the current unsaved changes.
        ///
        ///Do you wish to continue?.
        /// </summary>
        public static string ConfigRefreshWarning {
            get {
                return ResourceManager.GetString("ConfigRefreshWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving the configuration.
        ///
        ///If this continues, please inspect the log for the most recent error and report the problem.
        ///The error log can be opened by clicking the link below..
        /// </summary>
        public static string ConfigSaveError {
            get {
                return ResourceManager.GetString("ConfigSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes to the currently open configuration.
        ///
        ///Do you wish to save the changes?.
        /// </summary>
        public static string ConfigSavePrompt {
            get {
                return ResourceManager.GetString("ConfigSavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected destination is read only.
        ///
        ///Please choose a writable destination and try again..
        /// </summary>
        public static string ConfigSaveReadOnly {
            get {
                return ResourceManager.GetString("ConfigSaveReadOnly", resourceCulture);
            }
        }
    }
}
