//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeepConfigEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OptionsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OptionsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeepConfigEditor.Resources.OptionsRes", typeof(OptionsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepConfig Editor options.
        /// </summary>
        public static string OptionsStatusMessage {
            get {
                return ResourceManager.GetString("OptionsStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In menu.
        /// </summary>
        public static string RecentInMenu {
            get {
                return ResourceManager.GetString("RecentInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of recently edited sources to show in the Sources menu..
        /// </summary>
        public static string RecentInMenuTooltip {
            get {
                return ResourceManager.GetString("RecentInMenuTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Sources.
        /// </summary>
        public static string RecentSources {
            get {
                return ResourceManager.GetString("RecentSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In total.
        /// </summary>
        public static string RecentTotal {
            get {
                return ResourceManager.GetString("RecentTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of recently edited sources to remember in total. These are displayed various places..
        /// </summary>
        public static string RecentTotalTooltip {
            get {
                return ResourceManager.GetString("RecentTotalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference paths.
        /// </summary>
        public static string ReferencePaths {
            get {
                return ResourceManager.GetString("ReferencePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference paths exclusive to the current configuration.
        /// </summary>
        public static string ReferencePathsConfigSpecific {
            get {
                return ResourceManager.GetString("ReferencePathsConfigSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference paths specified here will only apply to the current configuration. This is tied to the entry of the configuration in the most recent list..
        /// </summary>
        public static string ReferencePathsConfigSpecificTooltip {
            get {
                return ResourceManager.GetString("ReferencePathsConfigSpecificTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
    }
}
